version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wlafayettekorea-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production
